# build environment
FROM node as build
WORKDIR /code
ENV PATH /code/node_modules/.bin:$PATH
COPY package.json ./
COPY package-lock.json ./
RUN npm ci --silent
RUN npm install react-scripts@4.0.3 -g --silent
COPY . ./
RUN npm run build

# production environment
FROM nginx:stable-alpine
COPY --from=build /code/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80/tcp 443/tcp

RUN apk update && apk add --no-cache bash certbot certbot-nginx
VOLUME /etc/letsencrypt
COPY startup.sh startup.sh
RUN chmod +x startup.sh
CMD ./startup.sh