version: "3.7"

services:
    backend:
      build:
        context: .
      hostname: backend
      volumes:
        - '.:/code'
      ports:
        - 8000:8000
      networks:
        - backend
      restart: always

    frontend:
      build:
        context: ./frontend
        dockerfile: ./Dockerfile-production
      ports:
        - '80:80'
      depends_on:
        - backend
      restart: always
      networks:
        - backend

networks:
  backend: