version: "3.7"

services:
    backend:
      build:
        context: .
        #target: ${TARGET:-development}
      hostname: backend
      volumes:
        - '.:/code'
      command: python manage.py runserver 0.0.0.0:8000
      networks:
        - local_network
      restart: always
      ports:
        - "8000:8000"
    frontend:
      build:
        context: ./frontend
        target: ${TARGET:-development}
      hostname: frontend
      volumes:
        - './frontend:/code'
      command: npm start
      restart: always
      networks:
        - local_network
      ports:
        - "3000:3000"

networks:
  local_network:
