version: "3.7"

services:
    backend:
      build:
        context: .
        target: ${TARGET:-production}
      hostname: backend
      volumes:
        - '.:/code'
      command: gunicorn backend.wsgi:application -c gunicorn.config.py --bind 0.0.0.0:8000 --log-file=- --log-level debu --log-file=- --log-level debug
      ports:
        - 8000:8000
      networks:
        - backend
      restart: always

    frontend:
      build:
        context: ./frontend
        dockerfile: ./Dockerfile-production
      ports:
        - '1337:80'
      depends_on:
        - backend
      restart: always
      networks:
        - backend

networks:
  backend: