version: "3.7"

services:

    postgres:
      image: postgres:13
      hostname: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        #TODO: Make user and password a docker secret
        #POSTGRES_DB_FILE: /run/secrets/postgres_db
        #POSTGRES_USER_FILE: /run/secrets/postgres_user
        #POSTGRES_PASSWORD_FILE: /run/secrets/postgres_pw
      #secrets: [postgres_db, postgres_user, postgres_pass]
      volumes: 
        - ./data/db:/var/lib/postgresql/data
        - ./scripts/:/docker-entrypoint-initdb.d/
      networks: [ backend ]
      restart: always

    backend:
      build:
        context: .
      environment:
        - DJANGO_CONFIGURATION=Production
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      hostname: backend
      volumes:
        - '.:/code'
      ports:
        - 8000:8000
      networks:
        - backend
      restart: always
      depends_on:
        - postgres

    frontend:
      build:
        context: ./frontend
        dockerfile: ./Dockerfile-production
      volumes:
        - ./certbot/www:/var/www/certbot/:ro
        - ./certbot/conf/:/etc/nginx/ssl/:ro
      ports:
        - 80:80
        - 443:443
      depends_on:
        - backend
      restart: always
      networks:
        - backend

    certbot:
      image: certbot/certbot
      volumes:
        - ./certbot/www/:/var/www/certbot/:rw
        - ./certbot/conf/:/etc/letsencrypt/:rw


networks:
  backend:

volumes:
  postgres_data:
