# Generated by Django 4.0.2 on 2022-02-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('movie_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
