# Generated by Django 4.0.2 on 2022-03-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmer', '0004_alter_reaction_movie_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='seen',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
