# Generated by Django 4.0.2 on 2022-02-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='r_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
